server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/testsecurity?characterEncoding=utf8
      username: root
      password: 1234
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
securityconfig:
    logoutsuccessurl: /
    permitall: /rest/**,/bbs**
    deniedpage: /deny
    urlroles: /**/new/**=admin;
              /**/edit/**=admin,editor;
              /**/delete/**=admin